name: build_and_test

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      publish_packages:
        required: false
        default: 'false'
        type: string

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-0|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: |
          conda install --yes pre-commit
          pre-commit run --all-files --show-diff-on-failure
  compute-matrices:
    needs: checks
    runs-on: ubuntu-latest
    outputs:
      BUILD_MATRIX: ${{ steps.compute-matrix.outputs.BUILD_MATRIX }}
      TEST_MATRIX: ${{ steps.compute-matrix.outputs.TEST_MATRIX }}
    steps:
      - name: Compute Build Matrix
        id: compute-matrix
        run: |
          set -eo pipefail

          # please keep the matrices sorted in ascending order by the following:
          #
          #     [ARCH, PY_VER, CUDA_VER, LINUX_VER, GPU, DRIVER]
          #
          export BUILD_MATRIX="
          # amd64
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '12.9.1', LINUX_VER: 'rockylinux8' }
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '13.0.0', LINUX_VER: 'rockylinux8' }
          # arm64
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '12.9.1', LINUX_VER: 'rockylinux8' }
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '13.0.0', LINUX_VER: 'rockylinux8' }
          "

          BUILD_MATRIX="$(
            yq -n -o json 'env(BUILD_MATRIX)' | \
            jq -c '{include: .}'
          )"

          echo "BUILD_MATRIX=${BUILD_MATRIX}" | tee --append "${GITHUB_OUTPUT}"

          export TEST_MATRIX="
          # amd64
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '12.0.1', LINUX_VER: 'ubuntu22.04', gpu: 'l4',   driver: 'earliest' }
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '12.2.2', LINUX_VER: 'ubuntu22.04', gpu: 'a100', driver: 'earliest' }
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '12.9.1', LINUX_VER: 'ubuntu24.04', gpu: 'a100', driver: 'latest' }
          - { ARCH: 'amd64', PY_VER: '3.13', CUDA_VER: '13.0.0', LINUX_VER: 'ubuntu24.04', gpu: 'a100', driver: 'latest' }
          # arm64
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '12.0.1', LINUX_VER: 'ubuntu22.04', gpu: 'l4',   driver: 'earliest' }
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '12.2.2', LINUX_VER: 'ubuntu22.04', gpu: 'a100', driver: 'earliest' }
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '12.9.1', LINUX_VER: 'ubuntu24.04', gpu: 'a100', driver: 'latest' }
          - { ARCH: 'arm64', PY_VER: '3.13', CUDA_VER: '13.0.0', LINUX_VER: 'ubuntu24.04', gpu: 'a100', driver: 'latest' }
          "

          TEST_MATRIX="$(
            yq -n -o json 'env(TEST_MATRIX)' | \
            jq -c '{include: .}'
          )"

          echo "TEST_MATRIX=${TEST_MATRIX}" | tee --append "${GITHUB_OUTPUT}"
  build:
    name:  build-${{ matrix.CUDA_VER }}, ${{ matrix.ARCH }}, ${{ matrix.LINUX_VER }}
    needs: compute-matrices
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrices.outputs.BUILD_MATRIX) }}
    runs-on: "linux-${{ matrix.ARCH }}-cpu16"
    container:
      image: "rapidsai/ci-wheel:cuda${{ matrix.CUDA_VER }}-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}"
      env:
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 900
      - name: checkout code repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Standardize repository information
        uses: rapidsai/shared-actions/rapids-github-info@main
      - name: Build and repair the wheel
        run: ci/build_wheel.sh
        env:
          GH_TOKEN: ${{ github.token }}
          RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
        # Use a shell that loads the rc file so that we get the compiler settings
        shell: bash -leo pipefail {0}
      - name: Get package name
        run: |
          RAPIDS_PY_CUDA_SUFFIX=$(rapids-wheel-ctk-name-gen ${RAPIDS_CUDA_VERSION})
          RAPIDS_PACKAGE_NAME=$(
            RAPIDS_NO_PKG_EXTENSION=true \
            RAPIDS_PY_WHEEL_PURE=1 \
            RAPIDS_PY_WHEEL_NAME="ucx_${RAPIDS_PY_CUDA_SUFFIX}" \
              rapids-package-name wheel_cpp
          )
          echo "RAPIDS_PACKAGE_NAME=${RAPIDS_PACKAGE_NAME}" >> "${GITHUB_OUTPUT}"
          echo "WHEEL_OUTPUT_DIR=${RAPIDS_WHEEL_BLD_OUTPUT_DIR}" >> "${GITHUB_OUTPUT}"
        id: package-name
      - name: Show files to be uploaded
        run: |
          echo "Contents of directory to be uploaded:"
          ls -R ${{ steps.package-name.outputs.WHEEL_OUTPUT_DIR }}
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: ${{ steps.package-name.outputs.RAPIDS_PACKAGE_NAME }}
          path: ${{ steps.package-name.outputs.WHEEL_OUTPUT_DIR }}
  test:
    name: test-${{ matrix.CUDA_VER }}, ${{ matrix.ARCH }}, ${{ matrix.LINUX_VER }}, ${{ matrix.gpu }}
    needs: [compute-matrices, build]
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrices.outputs.TEST_MATRIX) }}
      fail-fast: false
    runs-on: "linux-${{ matrix.ARCH }}-gpu-${{ matrix.gpu }}-${{ matrix.driver }}-1"
    container:
      image: "rapidsai/citestwheel:cuda${{ matrix.CUDA_VER }}-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        role-duration-seconds: 900
    - name: Run nvidia-smi to make sure GPU is working
      run: nvidia-smi
    - name: checkout code repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Standardize repository information
      uses: rapidsai/shared-actions/rapids-github-info@main
    - name: Run tests
      run: ci/test_wheel.sh
      env:
        GH_TOKEN: ${{ github.token }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
  publish:
    if: ${{ inputs.publish_packages == 'true' }}
    needs: test
    runs-on: linux-amd64-cpu4
    container:
      image: "rapidsai/ci-wheel:latest"
      env:
        GH_TOKEN: ${{ github.token }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        role-duration-seconds: 900
    - name: checkout code repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Get current date
      id: date
      run: |
        echo "CURRENT_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
    - name: Standardize repository information
      uses: rapidsai/shared-actions/rapids-github-info@main
    - name: Download wheels from artifact storage and publish to anaconda repository
      env:
        RAPIDS_CONDA_TOKEN: ${{ secrets.CONDA_RAPIDSAI_WHEELS_NIGHTLY_TOKEN }}
      run: |
        rapids-wheels-anaconda-github ucx cpp
